language: node_js

node_js:
  - "10.19.0"
  - "11.10.1"
yarn:
  - "1.13.0"

before_script:
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  - selenium-standalone start &
  - sleep 5